import { useState } from 'react';
import useToast from '../../hooks/useToast';
import useAuth from '../../hooks/useAuth';
import useFetch from '../../hooks/useFetch';
import Loader from '../../components/common/Loader';
import Button from '../../components/common/Button';
import inquiryService from '../../api/inquiryService';
import negotiationService from '../../api/negotiationService';
import agreementService from '../../api/agreementService';
import { formatDate, formatPKR } from '../../utils/formatters';

const STATUS_OPTIONS=['pending','under_review','negotiating','approved','rejected','agreement','completed'];

export default function MyInquiries(){
 const {isAdmin}=useAuth(); const toast=useToast(); const {data,loading,refetch}=useFetch(()=>inquiryService.getAll(),[]); const inquiries=data?.data?.inquiries||[];
 const [open,setOpen]=useState(null); const [messages,setMessages]=useState([]); const [text,setText]=useState(''); const [saving,setSaving]=useState(false);
 const openChat=async(id)=>{setOpen(id);try{const r=await negotiationService.list(id);setMessages(r.data?.data?.messages||[]);}catch(err){toast.error(err.friendlyMessage||'Could not load negotiation.')}};
 const send=async()=>{if(!text.trim())return;setSaving(true);try{await negotiationService.send(open,text);setText('');await openChat(open);}catch(err){toast.error(err.friendlyMessage||'Could not send message.')}finally{setSaving(false)}};
 const status=async(id,value)=>{try{await inquiryService.updateStatus(id,value);toast.success('Request status updated.');refetch();}catch(err){toast.error(err.friendlyMessage||'Could not update status.')}};
 const respond=async(id)=>{const value=window.prompt('Admin response');if(value===null)return;try{await inquiryService.update(id,{adminResponse:value,status:'negotiating'});toast.success('Response sent.');refetch();}catch(err){toast.error(err.friendlyMessage||'Could not send response.')}};
 const complete=async(id)=>{if(!window.confirm('Mark this deal as completed?'))return;try{await agreementService.complete(id);toast.success('Deal completed and agreement created.');refetch();}catch(err){toast.error(err.friendlyMessage||'Could not complete deal.')}};
 return <div><h1 className="h4 fw-bold mb-4">{isAdmin?'Plot Requests':'My Plot Requests'}</h1>{loading?<Loader label="Loading requests…"/>:inquiries.length===0?<div className="scj-card p-5 text-center"><i className="bi bi-chat-left-text fs-1 text-scj-gold d-block mb-3"/><p className="text-muted mb-0">No plot requests yet.</p></div>:<div className="row g-4">{inquiries.map(i=><div className="col-12" key={i._id}><div className="scj-card p-4"><div className="d-flex justify-content-between align-items-start gap-3 flex-wrap"><div><h2 className="h6 fw-bold mb-1">{i.property?.title||'Custom Plot Request'}</h2><div className="small text-muted">{i.name} · {i.email} · {i.phone}</div></div><span className="badge text-capitalize bg-secondary">{i.status}</span></div><div className="row g-3 mt-2 small"><div className="col-md-3"><strong>Budget:</strong> {formatPKR(i.budget)}</div><div className="col-md-2"><strong>Size:</strong> {i.plotSizeSqYds||'Custom'} Sq.Yds</div><div className="col-md-2"><strong>Type:</strong> {i.plotType}</div><div className="col-md-2"><strong>Income:</strong> {i.income?formatPKR(i.income):'—'}</div><div className="col-md-3"><strong>Date:</strong> {formatDate(i.createdAt)}</div></div>{i.adminResponse&&<div className="alert alert-success mt-3 mb-0"><strong>Admin response:</strong> {i.adminResponse}</div>}<p className="mt-3 mb-3">{i.message}</p>{isAdmin&&<div className="d-flex flex-wrap gap-2"><select className="form-select form-select-sm" style={{maxWidth:180}} value={i.status} onChange={e=>status(i._id,e.target.value)}>{STATUS_OPTIONS.map(s=><option key={s}>{s}</option>)}</select><Button size="sm" onClick={()=>respond(i._id)}>Respond</Button><button className="btn btn-sm btn-outline-primary" onClick={()=>openChat(i._id)}>Negotiation</button>{['agreement','approved'].includes(i.status)&&<button className="btn btn-sm btn-success" onClick={()=>complete(i._id)}>Complete Deal</button>}</div>} {!isAdmin&&<button className="btn btn-sm btn-outline-primary" onClick={()=>openChat(i._id)}>Open Negotiation</button>}{open===i._id&&<div className="border rounded p-3 mt-3 bg-light"><div className="mb-2 fw-semibold">Negotiation</div><div style={{maxHeight:220,overflowY:'auto'}}>{messages.map(m=><div key={m._id} className={`mb-2 ${String(m.sender?._id)===String(i.user?._id)?'':'text-end'}`}><span className="d-inline-block p-2 rounded bg-white border small">{m.message}<br/><small className="text-muted">{m.sender?.name||'User'} · {formatDate(m.createdAt)}</small></span></div>)}</div><div className="input-group mt-2"><input className="form-control" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Write a message…"/><button className="btn btn-scj-primary" disabled={saving} onClick={send}>Send</button></div></div>}</div></div>)}</div>}</div>
}
